# Generated by Django 6.0.2 on 2026-02-07 19:11

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_category_icon_alter_server_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.serverBannerUploadPath, validators=[server.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.serverIconUploadPath, validators=[server.validators.validate_icon_image_size, server.validators.validate_image_file_extension]),
        ),
    ]
